import {
  inventory,
  type LowerCategoryInventorySeed,
} from "@/lib/openai/api-setting-inventory-shared";

export const API_SETTING_INVENTORY_15_18_SEEDS = [
  ...inventory("batches", "Batches > Inventory", "placeholder", [
    [
      "input-file",
      "batch input file",
      "バッチ入力ファイル",
      "大量のAPIリクエストをまとめた入力ファイルです。",
    ],
    [
      "endpoint-target",
      "endpoint target",
      "対象API機能",
      "まとめて実行する対象のAPI機能です。",
    ],
    [
      "completion-window",
      "completion_window",
      "完了期限",
      "バッチ処理を完了させる時間枠です。",
    ],
    [
      "cancel",
      "Cancel batch",
      "バッチ中止",
      "進行中のバッチ処理を中止するAPI操作です。",
    ],
    [
      "output-file",
      "output_file_id",
      "結果ファイル",
      "成功した処理結果が入るファイルです。",
    ],
    [
      "error-file",
      "error_file_id",
      "エラーファイル",
      "失敗内容が入るファイルです。",
    ],
    [
      "request-counts",
      "request_counts",
      "リクエスト件数",
      "完了・失敗・処理中の件数を示します。",
    ],
    [
      "metadata",
      "metadata",
      "管理用メタデータ",
      "バッチを管理・識別するための補助情報です。",
    ],
    [
      "expires-at",
      "expires_at",
      "有効期限",
      "バッチ結果を扱える期限に関係する情報です。",
    ],
  ]),
  ...inventory("fine-tuning", "Fine-tuning > Inventory", "needs-confirmation", [
    [
      "training-file",
      "training_file",
      "学習ファイル",
      "追加学習に使う例題データです。",
    ],
    [
      "validation-file",
      "validation_file",
      "検証ファイル",
      "学習結果を確認するためのデータです。",
    ],
    ["base-model", "model", "ベースモデル", "追加学習の元になるモデルです。"],
    [
      "hyperparameters",
      "hyperparameters",
      "学習パラメータ",
      "学習回数など学習方法を調整する設定です。",
    ],
    ["status", "job status", "ジョブ状態", "追加学習の進行状態を示します。"],
    [
      "events",
      "job events",
      "ジョブイベント",
      "追加学習中に起きた出来事の記録です。",
    ],
    ["cancel", "Cancel job", "学習中止", "追加学習を中止するAPI操作です。"],
    [
      "pause",
      "Pause job",
      "学習一時停止",
      "追加学習を一時停止するAPI操作候補です。",
    ],
    [
      "resume",
      "Resume job",
      "学習再開",
      "一時停止した追加学習を再開するAPI操作候補です。",
    ],
    [
      "permissions",
      "model permissions",
      "モデル権限",
      "学習済みモデルを使える範囲に関係します。",
    ],
    [
      "integrations",
      "integrations",
      "外部連携",
      "学習状況の追跡などに使う外部連携設定です。",
    ],
    [
      "seed",
      "seed",
      "学習再現用シード",
      "学習結果の再現性に関係する数値です。",
    ],
    [
      "suffix",
      "suffix",
      "モデル名サフィックス",
      "学習済みモデル名につける識別用文字列です。",
    ],
  ]),
  ...inventory("evals", "Evals > Inventory", "needs-confirmation", [
    [
      "definition",
      "eval definition",
      "評価定義",
      "何をどの基準で評価するかをまとめた定義です。",
    ],
    [
      "dataset",
      "dataset",
      "評価データ",
      "品質確認に使う入力や期待結果の集合です。",
    ],
    [
      "data-source",
      "data source",
      "評価データ元",
      "評価に使うデータの取得元です。",
    ],
    [
      "testing-criteria",
      "testing criteria",
      "評価条件",
      "合格と判断する条件です。",
    ],
    [
      "output-items",
      "output items",
      "評価出力項目",
      "評価実行から得られる個別結果です。",
    ],
    ["status", "run status", "評価状態", "評価実行の進行状態です。"],
    ["errors", "run errors", "評価エラー", "評価実行中に発生した問題です。"],
    [
      "metadata",
      "metadata",
      "評価管理情報",
      "評価を識別・整理するための補助情報です。",
    ],
  ]),
  ...inventory("graders", "Graders > Inventory", "needs-confirmation", [
    [
      "type",
      "grader type",
      "採点方式",
      "回答をどの方法で採点するかを示します。",
    ],
    ["score", "score", "スコア", "回答の評価結果を数値で示します。"],
    ["pass-fail", "pass / fail", "合否", "回答が基準を満たしたかを示します。"],
    [
      "validate",
      "Validate grader",
      "採点器検証",
      "採点設定が正しく使えるか確認するAPI操作です。",
    ],
    ["input", "grader input", "採点入力", "採点対象として渡す内容です。"],
    [
      "reference-answer",
      "reference answer",
      "参考解答",
      "採点時に比較する期待回答です。",
    ],
    [
      "model-grader",
      "model grader",
      "モデル採点",
      "別のモデルを使って回答を評価する方式です。",
    ],
    [
      "string-check",
      "string check grader",
      "文字列チェック",
      "特定文字列や形式を満たすか確認する方式です。",
    ],
    [
      "text-similarity",
      "text similarity grader",
      "文章類似度",
      "期待回答との意味や表現の近さを測る方式です。",
    ],
  ]),
] satisfies readonly LowerCategoryInventorySeed[];
