export type LowerCategoryInventorySeed = {
  categoryId: string;
  id: string;
  japaneseName: string;
  officialName: string;
  shortDescription: string;
  status:
    | "admin"
    | "legacy"
    | "needs-confirmation"
    | "placeholder"
    | "unsupported";
  uiPlacement: string;
};

const inventory = (
  categoryId: string,
  uiPlacement: string,
  status: LowerCategoryInventorySeed["status"],
  items: readonly (readonly [string, string, string, string])[],
) =>
  items.map(([id, officialName, japaneseName, shortDescription]) => ({
    categoryId,
    id: `${categoryId}-${id}`,
    japaneseName,
    officialName,
    shortDescription,
    status,
    uiPlacement,
  }));

export const LOWER_CATEGORY_INVENTORY_SEEDS = [
  ...inventory(
    "chat-completions",
    "Chat Completions > Legacy inventory",
    "legacy",
    [
      [
        "model",
        "model",
        "旧APIモデル指定",
        "旧チャット補完で使うモデルを指定する項目です。",
      ],
      [
        "max-completion-tokens",
        "max_completion_tokens",
        "旧API最大出力トークン",
        "旧チャット補完の応答長上限です。",
      ],
      [
        "temperature",
        "temperature",
        "旧API生成の揺らぎ",
        "旧チャット補完で候補の選び方を調整する項目です。",
      ],
      [
        "top-p",
        "top_p",
        "旧API候補範囲",
        "旧チャット補完で単語候補の範囲を調整する項目です。",
      ],
      [
        "tools",
        "tools",
        "旧APIツール",
        "旧チャット補完でツール候補を渡す項目です。",
      ],
      [
        "tool-choice",
        "tool_choice",
        "旧APIツール選択",
        "旧チャット補完で使うツールを選ぶ項目です。",
      ],
      [
        "response-format",
        "response_format",
        "旧API応答形式",
        "旧チャット補完の返答形式を指定する項目です。",
      ],
      [
        "stop",
        "stop",
        "旧API停止条件",
        "旧チャット補完の生成を止める文字列候補です。",
      ],
      [
        "logprobs",
        "logprobs",
        "旧API候補確率",
        "旧チャット補完の候補確率情報です。",
      ],
      [
        "seed",
        "seed",
        "旧API再現用シード",
        "旧チャット補完の再現性に関係する項目です。",
      ],
      [
        "service-tier",
        "service_tier",
        "旧APIサービス階層",
        "旧チャット補完の処理階層に関係する項目です。",
      ],
      [
        "modalities",
        "modalities",
        "旧API出力モード",
        "旧チャット補完の出力種類を指定する候補です。",
      ],
      [
        "audio",
        "audio",
        "旧API音声出力",
        "旧チャット補完の音声出力に関係する候補です。",
      ],
    ],
  ),
  ...inventory("moderations", "Moderations > Results", "placeholder", [
    ["model", "model", "判定モデル", "安全性判定に使うモデルです。"],
    [
      "categories",
      "categories",
      "判定カテゴリ",
      "どの種類の安全性リスクに当てはまるかを示します。",
    ],
    [
      "category-scores",
      "category_scores",
      "カテゴリ別スコア",
      "安全性カテゴリごとの判定の強さを示します。",
    ],
    [
      "flagged",
      "flagged",
      "要注意判定",
      "入力や出力が要注意と判定されたかを示します。",
    ],
    [
      "multimodal-input",
      "multimodal input",
      "画像を含む安全性判定",
      "テキスト以外も含めて安全性を確認する候補です。",
    ],
  ]),
  ...inventory("files", "Files > Inventory", "placeholder", [
    [
      "list",
      "List files",
      "ファイル一覧",
      "OpenAI側に置かれたファイルの一覧を確認するAPI操作です。",
    ],
    [
      "retrieve",
      "Retrieve file",
      "ファイル情報取得",
      "特定ファイルの名前や用途などを確認するAPI操作です。",
    ],
    [
      "content",
      "Retrieve file content",
      "ファイル内容取得",
      "特定ファイルの内容を取得するAPI操作です。",
    ],
    [
      "delete",
      "Delete file",
      "ファイル削除",
      "OpenAI側のファイルを削除する破壊的なAPI操作です。",
    ],
    [
      "status",
      "file status",
      "ファイル状態",
      "アップロードや処理の進行状態を示します。",
    ],
    [
      "expires-after",
      "expires_after",
      "ファイル有効期限",
      "ファイルをいつまで保持するかに関係する設定です。",
    ],
    [
      "bytes",
      "bytes",
      "ファイルサイズ",
      "ファイルの大きさをバイト単位で示します。",
    ],
    [
      "filename",
      "filename",
      "ファイル名",
      "アップロードされたファイルの名前です。",
    ],
  ]),
  ...inventory("uploads", "Uploads > Inventory", "placeholder", [
    [
      "create",
      "Create upload",
      "大容量アップロード開始",
      "分割アップロードを開始するAPI操作です。",
    ],
    [
      "metadata",
      "upload metadata",
      "アップロード情報",
      "ファイル名や用途などの補助情報です。",
    ],
    [
      "mime-type",
      "mime_type",
      "ファイル形式",
      "アップロードするデータの種類を示します。",
    ],
    ["size", "bytes", "合計サイズ", "分割して送るデータ全体の大きさです。"],
    [
      "status",
      "upload status",
      "アップロード状態",
      "分割アップロードの進行状態を示します。",
    ],
    [
      "expires-at",
      "expires_at",
      "アップロード有効期限",
      "分割アップロードを完了できる期限です。",
    ],
  ]),
  ...inventory("vector-stores", "Vector Stores > Inventory", "placeholder", [
    [
      "list",
      "List vector stores",
      "ベクトルストア一覧",
      "検索用データ置き場の一覧を確認するAPI操作です。",
    ],
    [
      "retrieve",
      "Retrieve vector store",
      "ベクトルストア情報取得",
      "検索用データ置き場の状態を確認するAPI操作です。",
    ],
    [
      "update",
      "Update vector store",
      "ベクトルストア更新",
      "検索用データ置き場の設定を変更するAPI操作です。",
    ],
    [
      "delete",
      "Delete vector store",
      "ベクトルストア削除",
      "検索用データ置き場を削除する破壊的なAPI操作です。",
    ],
    [
      "search",
      "Search vector store",
      "ベクトル検索",
      "保存した文書から関連情報を探すAPI操作です。",
    ],
    [
      "files",
      "Vector store files",
      "登録ファイル",
      "検索用データ置き場に登録されたファイルです。",
    ],
    [
      "retrieve-file",
      "Retrieve vector store file",
      "登録ファイル情報取得",
      "登録済みファイルの状態を確認するAPI操作です。",
    ],
    [
      "delete-file",
      "Delete vector store file",
      "登録ファイル削除",
      "検索対象からファイルを外す破壊的なAPI操作です。",
    ],
    [
      "file-content",
      "Retrieve vector store file content",
      "解析済み内容取得",
      "検索用に解析されたファイル内容を確認するAPI操作です。",
    ],
    [
      "status",
      "vector store status",
      "処理状態",
      "検索できる状態まで準備できたかを示します。",
    ],
    [
      "expires-after",
      "expires_after",
      "有効期限",
      "検索用データ置き場を保持する期間です。",
    ],
    [
      "usage-bytes",
      "usage_bytes",
      "使用容量",
      "検索用データ置き場が使う容量です。",
    ],
    [
      "filters",
      "attribute filters",
      "検索絞り込み",
      "補助情報を使って検索対象を絞る設定です。",
    ],
    [
      "ranking-options",
      "ranking_options",
      "検索順位調整",
      "検索結果の並び方や採用基準を調整する設定です。",
    ],
  ]),
  ...inventory("models", "Models > Inventory", "needs-confirmation", [
    [
      "owned-by",
      "owned_by",
      "所有者情報",
      "モデルを提供・所有する主体を示す情報です。",
    ],
    [
      "created",
      "created",
      "作成日時",
      "モデルが作成された日時を示す情報です。",
    ],
    [
      "capabilities",
      "model capabilities",
      "対応機能",
      "モデルが扱える入力や機能を示す候補情報です。",
    ],
    [
      "access",
      "model access",
      "モデル利用権限",
      "組織やプロジェクトでモデルを使えるかに関係します。",
    ],
    [
      "delete",
      "Delete fine-tuned model",
      "学習済みモデル削除",
      "学習済みモデルを削除する破壊的なAPI操作です。",
    ],
  ]),
  ...inventory("batches", "Batches > Inventory", "placeholder", [
    [
      "input-file",
      "batch input file",
      "バッチ入力ファイル",
      "大量のAPIリクエストをまとめた入力ファイルです。",
    ],
    [
      "endpoint-target",
      "endpoint target",
      "対象API機能",
      "まとめて実行する対象のAPI機能です。",
    ],
    [
      "completion-window",
      "completion_window",
      "完了期限",
      "バッチ処理を完了させる時間枠です。",
    ],
    [
      "cancel",
      "Cancel batch",
      "バッチ中止",
      "進行中のバッチ処理を中止するAPI操作です。",
    ],
    [
      "output-file",
      "output_file_id",
      "結果ファイル",
      "成功した処理結果が入るファイルです。",
    ],
    [
      "error-file",
      "error_file_id",
      "エラーファイル",
      "失敗内容が入るファイルです。",
    ],
    [
      "request-counts",
      "request_counts",
      "リクエスト件数",
      "完了・失敗・処理中の件数を示します。",
    ],
    [
      "metadata",
      "metadata",
      "管理用メタデータ",
      "バッチを管理・識別するための補助情報です。",
    ],
    [
      "expires-at",
      "expires_at",
      "有効期限",
      "バッチ結果を扱える期限に関係する情報です。",
    ],
  ]),
  ...inventory("fine-tuning", "Fine-tuning > Inventory", "needs-confirmation", [
    [
      "training-file",
      "training_file",
      "学習ファイル",
      "追加学習に使う例題データです。",
    ],
    [
      "validation-file",
      "validation_file",
      "検証ファイル",
      "学習結果を確認するためのデータです。",
    ],
    ["base-model", "model", "ベースモデル", "追加学習の元になるモデルです。"],
    [
      "hyperparameters",
      "hyperparameters",
      "学習パラメータ",
      "学習回数など学習方法を調整する設定です。",
    ],
    ["status", "job status", "ジョブ状態", "追加学習の進行状態を示します。"],
    [
      "events",
      "job events",
      "ジョブイベント",
      "追加学習中に起きた出来事の記録です。",
    ],
    ["cancel", "Cancel job", "学習中止", "追加学習を中止するAPI操作です。"],
    [
      "pause",
      "Pause job",
      "学習一時停止",
      "追加学習を一時停止するAPI操作候補です。",
    ],
    [
      "resume",
      "Resume job",
      "学習再開",
      "一時停止した追加学習を再開するAPI操作候補です。",
    ],
    [
      "permissions",
      "model permissions",
      "モデル権限",
      "学習済みモデルを使える範囲に関係します。",
    ],
    [
      "integrations",
      "integrations",
      "外部連携",
      "学習状況の追跡などに使う外部連携設定です。",
    ],
    [
      "seed",
      "seed",
      "学習再現用シード",
      "学習結果の再現性に関係する数値です。",
    ],
    [
      "suffix",
      "suffix",
      "モデル名サフィックス",
      "学習済みモデル名につける識別用文字列です。",
    ],
  ]),
  ...inventory("evals", "Evals > Inventory", "needs-confirmation", [
    [
      "definition",
      "eval definition",
      "評価定義",
      "何をどの基準で評価するかをまとめた定義です。",
    ],
    [
      "dataset",
      "dataset",
      "評価データ",
      "品質確認に使う入力や期待結果の集合です。",
    ],
    [
      "data-source",
      "data source",
      "評価データ元",
      "評価に使うデータの取得元です。",
    ],
    [
      "testing-criteria",
      "testing criteria",
      "評価条件",
      "合格と判断する条件です。",
    ],
    [
      "output-items",
      "output items",
      "評価出力項目",
      "評価実行から得られる個別結果です。",
    ],
    ["status", "run status", "評価状態", "評価実行の進行状態です。"],
    ["errors", "run errors", "評価エラー", "評価実行中に発生した問題です。"],
    [
      "metadata",
      "metadata",
      "評価管理情報",
      "評価を識別・整理するための補助情報です。",
    ],
  ]),
  ...inventory("graders", "Graders > Inventory", "needs-confirmation", [
    [
      "type",
      "grader type",
      "採点方式",
      "回答をどの方法で採点するかを示します。",
    ],
    ["score", "score", "スコア", "回答の評価結果を数値で示します。"],
    ["pass-fail", "pass / fail", "合否", "回答が基準を満たしたかを示します。"],
    [
      "validate",
      "Validate grader",
      "採点器検証",
      "採点設定が正しく使えるか確認するAPI操作です。",
    ],
    ["input", "grader input", "採点入力", "採点対象として渡す内容です。"],
    [
      "reference-answer",
      "reference answer",
      "参考解答",
      "採点時に比較する期待回答です。",
    ],
    [
      "model-grader",
      "model grader",
      "モデル採点",
      "別のモデルを使って回答を評価する方式です。",
    ],
    [
      "string-check",
      "string check grader",
      "文字列チェック",
      "特定文字列や形式を満たすか確認する方式です。",
    ],
    [
      "text-similarity",
      "text similarity grader",
      "文章類似度",
      "期待回答との意味や表現の近さを測る方式です。",
    ],
  ]),
  ...inventory("webhooks", "Webhooks > Inventory", "needs-confirmation", [
    [
      "event-type",
      "event type",
      "イベント種別",
      "どの出来事の通知かを示します。",
    ],
    [
      "endpoint-url",
      "endpoint URL",
      "通知先URL",
      "イベント通知を受け取るサーバーの場所です。",
    ],
    [
      "secret",
      "webhook secret",
      "署名シークレット",
      "通知が本物か確認するための秘密情報です。",
    ],
    [
      "retry",
      "delivery retry",
      "再送",
      "通知に失敗した場合の再送に関係します。",
    ],
    [
      "delivery-status",
      "delivery status",
      "配信状態",
      "通知が届いたかを示します。",
    ],
    [
      "event-id",
      "event id",
      "イベントID",
      "通知を重複処理しないための識別子です。",
    ],
    [
      "event-created-at",
      "event created_at",
      "イベント発生日時",
      "通知対象の出来事が発生した日時です。",
    ],
  ]),
  ...inventory("containers", "Containers > Inventory", "unsupported", [
    [
      "lifecycle",
      "container lifecycle",
      "コンテナ状態",
      "実行環境の作成から終了までの状態です。",
    ],
    [
      "retrieve",
      "Retrieve container",
      "コンテナ情報取得",
      "実行環境の状態を確認するAPI操作です。",
    ],
    [
      "delete",
      "Delete container",
      "コンテナ削除",
      "実行環境を削除する破壊的なAPI操作です。",
    ],
    [
      "add-file",
      "Add container file",
      "コンテナへファイル追加",
      "実行環境へファイルを置くAPI操作です。",
    ],
    [
      "retrieve-file",
      "Retrieve container file",
      "コンテナファイル取得",
      "実行環境内のファイル情報を確認するAPI操作です。",
    ],
    [
      "retrieve-content",
      "Retrieve container file content",
      "内容取得",
      "実行環境内のファイル内容を取得するAPI操作です。",
    ],
    [
      "delete-file",
      "Delete container file",
      "コンテナファイル削除",
      "実行環境内のファイルを削除する破壊的なAPI操作です。",
    ],
    [
      "sandbox-boundary",
      "sandbox boundary",
      "実行境界",
      "コードやファイル操作を隔離する安全境界です。",
    ],
    [
      "expires-at",
      "expires_at",
      "コンテナ有効期限",
      "実行環境が保持される期限です。",
    ],
  ]),
  ...inventory("skills", "Skills > Inventory", "needs-confirmation", [
    [
      "content",
      "skill content",
      "スキル内容",
      "再利用する手順や知識の内容です。",
    ],
    [
      "versions",
      "skill versions",
      "スキルのバージョン",
      "スキル変更の履歴や版を管理する考え方です。",
    ],
    [
      "publish",
      "Publish skill",
      "スキル公開",
      "スキルを利用可能にする操作候補です。",
    ],
    [
      "update",
      "Update skill",
      "スキル更新",
      "既存スキルの内容を変更する操作候補です。",
    ],
    [
      "delete",
      "Delete skill",
      "スキル削除",
      "スキルを削除する破壊的な操作候補です。",
    ],
    [
      "permissions",
      "skill permissions",
      "スキル権限",
      "誰がスキルを利用・変更できるかに関係します。",
    ],
    [
      "runtime-boundary",
      "runtime boundary",
      "実行境界",
      "スキルが実行できる範囲を制限する考え方です。",
    ],
    [
      "dependencies",
      "skill dependencies",
      "依存機能",
      "スキルが必要とするツールや機能です。",
    ],
  ]),
  ...inventory("chatkit", "ChatKit > Inventory", "needs-confirmation", [
    [
      "session",
      "session",
      "セッション",
      "ChatKitの利用単位となる接続情報です。",
    ],
    ["thread", "thread", "スレッド", "ChatKit上の会話のまとまりです。"],
    [
      "thread-items",
      "thread items",
      "スレッド項目",
      "ChatKit上の会話に含まれる項目です。",
    ],
    [
      "cancel-session",
      "Cancel session",
      "セッション中止",
      "ChatKitセッションを中止するAPI操作候補です。",
    ],
    [
      "client-ui-boundary",
      "client UI boundary",
      "ChatKit UI境界",
      "ChatKitと4oSphere独自UIの役割分担です。",
    ],
    [
      "authentication",
      "authentication",
      "ChatKit認証",
      "ChatKit利用者を安全に識別する仕組みです。",
    ],
    [
      "domain-allowlist",
      "domain allowlist",
      "許可ドメイン",
      "ChatKitを表示できるWebサイトを制限する候補です。",
    ],
  ]),
  ...inventory("administration", "Administration > Inventory", "admin", [
    [
      "audit-logs",
      "audit logs",
      "監査ログ",
      "組織内の管理操作を追跡する記録です。",
    ],
    [
      "admin-api-keys",
      "admin API keys",
      "管理者APIキー",
      "組織管理APIに使う特に強い秘密鍵です。",
    ],
    ["usage", "usage", "利用量", "組織やプロジェクトのAPI利用量です。"],
    ["costs", "costs", "コスト", "組織やプロジェクトのAPI費用です。"],
    ["invites", "invites", "招待", "組織へユーザーを招待する管理操作です。"],
    ["users", "users", "ユーザー", "組織に所属するユーザーの管理対象です。"],
    ["roles", "roles", "ロール", "管理権限の種類です。"],
    ["groups", "groups", "グループ", "複数ユーザーをまとめる管理単位です。"],
    [
      "projects",
      "projects",
      "プロジェクト",
      "API利用や権限を分ける管理単位です。",
    ],
    [
      "service-accounts",
      "service accounts",
      "サービスアカウント",
      "サーバーや自動処理向けの管理アカウントです。",
    ],
    [
      "project-api-keys",
      "project API keys",
      "プロジェクトAPIキー",
      "プロジェクト単位の秘密鍵です。",
    ],
    [
      "rate-limits",
      "rate limits",
      "レート制限",
      "一定時間にAPIを使える量の上限です。",
    ],
    [
      "model-permissions",
      "model permissions",
      "モデル権限",
      "プロジェクトで利用できるモデルを制御します。",
    ],
    [
      "hosted-tool-permissions",
      "hosted tool permissions",
      "ホスト型ツール権限",
      "OpenAI側ツールの利用可否を制御します。",
    ],
    [
      "data-retention",
      "data retention",
      "データ保持",
      "APIデータを保持する期間や方針です。",
    ],
    [
      "spend-alerts",
      "spend alerts",
      "利用額アラート",
      "費用が基準を超えたときの通知設定です。",
    ],
    [
      "certificates",
      "certificates",
      "証明書",
      "通信や組織アクセスの確認に使う証明書です。",
    ],
  ]),
  ...inventory("legacy-apis", "Legacy APIs > Inventory", "legacy", [
    [
      "chat-completions-path",
      "Chat Completions legacy path",
      "旧チャット補完",
      "Responses以前から使われているチャット形式のAPIです。",
    ],
    [
      "threads",
      "Threads",
      "旧スレッド",
      "Assistants APIで会話をまとめる旧方式です。",
    ],
    ["runs", "Runs", "旧実行", "Assistants APIで回答生成を進める旧方式です。"],
    ["run-steps", "Run steps", "旧実行ステップ", "旧実行処理の途中経過です。"],
    [
      "messages",
      "Messages",
      "旧メッセージ",
      "Assistants APIのスレッド内メッセージです。",
    ],
    [
      "submit-tool-outputs",
      "Submit tool outputs",
      "旧ツール結果送信",
      "Assistants APIへツール結果を返す旧操作です。",
    ],
    [
      "migration-note",
      "migration note",
      "移行メモ",
      "旧APIから現在のAPIへ移る際の注意事項です。",
    ],
    [
      "deprecation-risk",
      "deprecation risk",
      "非推奨リスク",
      "旧APIが将来変更・終了する可能性に関する注意です。",
    ],
  ]),
] satisfies readonly LowerCategoryInventorySeed[];
