import {
  inventory,
  type LowerCategoryInventorySeed,
} from "@/lib/openai/api-setting-inventory-shared";

export const API_SETTING_INVENTORY_19_24_SEEDS = [
  ...inventory("webhooks", "Webhooks > Inventory", "needs-confirmation", [
    [
      "event-type",
      "event type",
      "イベント種別",
      "どの出来事の通知かを示します。",
    ],
    [
      "endpoint-url",
      "endpoint URL",
      "通知先URL",
      "イベント通知を受け取るサーバーの場所です。",
    ],
    [
      "secret",
      "webhook secret",
      "署名シークレット",
      "通知が本物か確認するための秘密情報です。",
    ],
    [
      "retry",
      "delivery retry",
      "再送",
      "通知に失敗した場合の再送に関係します。",
    ],
    [
      "delivery-status",
      "delivery status",
      "配信状態",
      "通知が届いたかを示します。",
    ],
    [
      "event-id",
      "event id",
      "イベントID",
      "通知を重複処理しないための識別子です。",
    ],
    [
      "event-created-at",
      "event created_at",
      "イベント発生日時",
      "通知対象の出来事が発生した日時です。",
    ],
  ]),
  ...inventory("containers", "Containers > Inventory", "unsupported", [
    [
      "lifecycle",
      "container lifecycle",
      "コンテナ状態",
      "実行環境の作成から終了までの状態です。",
    ],
    [
      "retrieve",
      "Retrieve container",
      "コンテナ情報取得",
      "実行環境の状態を確認するAPI操作です。",
    ],
    [
      "delete",
      "Delete container",
      "コンテナ削除",
      "実行環境を削除する破壊的なAPI操作です。",
    ],
    [
      "add-file",
      "Add container file",
      "コンテナへファイル追加",
      "実行環境へファイルを置くAPI操作です。",
    ],
    [
      "retrieve-file",
      "Retrieve container file",
      "コンテナファイル取得",
      "実行環境内のファイル情報を確認するAPI操作です。",
    ],
    [
      "retrieve-content",
      "Retrieve container file content",
      "内容取得",
      "実行環境内のファイル内容を取得するAPI操作です。",
    ],
    [
      "delete-file",
      "Delete container file",
      "コンテナファイル削除",
      "実行環境内のファイルを削除する破壊的なAPI操作です。",
    ],
    [
      "sandbox-boundary",
      "sandbox boundary",
      "実行境界",
      "コードやファイル操作を隔離する安全境界です。",
    ],
    [
      "expires-at",
      "expires_at",
      "コンテナ有効期限",
      "実行環境が保持される期限です。",
    ],
  ]),
  ...inventory("skills", "Skills > Inventory", "needs-confirmation", [
    [
      "content",
      "skill content",
      "スキル内容",
      "再利用する手順や知識の内容です。",
    ],
    [
      "versions",
      "skill versions",
      "スキルのバージョン",
      "スキル変更の履歴や版を管理する考え方です。",
    ],
    [
      "publish",
      "Publish skill",
      "スキル公開",
      "スキルを利用可能にする操作候補です。",
    ],
    [
      "update",
      "Update skill",
      "スキル更新",
      "既存スキルの内容を変更する操作候補です。",
    ],
    [
      "delete",
      "Delete skill",
      "スキル削除",
      "スキルを削除する破壊的な操作候補です。",
    ],
    [
      "permissions",
      "skill permissions",
      "スキル権限",
      "誰がスキルを利用・変更できるかに関係します。",
    ],
    [
      "runtime-boundary",
      "runtime boundary",
      "実行境界",
      "スキルが実行できる範囲を制限する考え方です。",
    ],
    [
      "dependencies",
      "skill dependencies",
      "依存機能",
      "スキルが必要とするツールや機能です。",
    ],
  ]),
  ...inventory("chatkit", "ChatKit > Inventory", "needs-confirmation", [
    [
      "session",
      "session",
      "セッション",
      "ChatKitの利用単位となる接続情報です。",
    ],
    ["thread", "thread", "スレッド", "ChatKit上の会話のまとまりです。"],
    [
      "thread-items",
      "thread items",
      "スレッド項目",
      "ChatKit上の会話に含まれる項目です。",
    ],
    [
      "cancel-session",
      "Cancel session",
      "セッション中止",
      "ChatKitセッションを中止するAPI操作候補です。",
    ],
    [
      "client-ui-boundary",
      "client UI boundary",
      "ChatKit UI境界",
      "ChatKitと4oSphere独自UIの役割分担です。",
    ],
    [
      "authentication",
      "authentication",
      "ChatKit認証",
      "ChatKit利用者を安全に識別する仕組みです。",
    ],
    [
      "domain-allowlist",
      "domain allowlist",
      "許可ドメイン",
      "ChatKitを表示できるWebサイトを制限する候補です。",
    ],
  ]),
  ...inventory("administration", "Administration > Inventory", "admin", [
    [
      "audit-logs",
      "audit logs",
      "監査ログ",
      "組織内の管理操作を追跡する記録です。",
    ],
    [
      "admin-api-keys",
      "admin API keys",
      "管理者APIキー",
      "組織管理APIに使う特に強い秘密鍵です。",
    ],
    ["usage", "usage", "利用量", "組織やプロジェクトのAPI利用量です。"],
    ["costs", "costs", "コスト", "組織やプロジェクトのAPI費用です。"],
    ["invites", "invites", "招待", "組織へユーザーを招待する管理操作です。"],
    ["users", "users", "ユーザー", "組織に所属するユーザーの管理対象です。"],
    ["roles", "roles", "ロール", "管理権限の種類です。"],
    ["groups", "groups", "グループ", "複数ユーザーをまとめる管理単位です。"],
    [
      "projects",
      "projects",
      "プロジェクト",
      "API利用や権限を分ける管理単位です。",
    ],
    [
      "service-accounts",
      "service accounts",
      "サービスアカウント",
      "サーバーや自動処理向けの管理アカウントです。",
    ],
    [
      "project-api-keys",
      "project API keys",
      "プロジェクトAPIキー",
      "プロジェクト単位の秘密鍵です。",
    ],
    [
      "rate-limits",
      "rate limits",
      "レート制限",
      "一定時間にAPIを使える量の上限です。",
    ],
    [
      "model-permissions",
      "model permissions",
      "モデル権限",
      "プロジェクトで利用できるモデルを制御します。",
    ],
    [
      "hosted-tool-permissions",
      "hosted tool permissions",
      "ホスト型ツール権限",
      "OpenAI側ツールの利用可否を制御します。",
    ],
    [
      "data-retention",
      "data retention",
      "データ保持",
      "APIデータを保持する期間や方針です。",
    ],
    [
      "spend-alerts",
      "spend alerts",
      "利用額アラート",
      "費用が基準を超えたときの通知設定です。",
    ],
    [
      "certificates",
      "certificates",
      "証明書",
      "通信や組織アクセスの確認に使う証明書です。",
    ],
  ]),
  ...inventory("legacy-apis", "Legacy APIs > Inventory", "legacy", [
    [
      "chat-completions-path",
      "Chat Completions legacy path",
      "旧チャット補完",
      "Responses以前から使われているチャット形式のAPIです。",
    ],
    [
      "threads",
      "Threads",
      "旧スレッド",
      "Assistants APIで会話をまとめる旧方式です。",
    ],
    ["runs", "Runs", "旧実行", "Assistants APIで回答生成を進める旧方式です。"],
    ["run-steps", "Run steps", "旧実行ステップ", "旧実行処理の途中経過です。"],
    [
      "messages",
      "Messages",
      "旧メッセージ",
      "Assistants APIのスレッド内メッセージです。",
    ],
    [
      "submit-tool-outputs",
      "Submit tool outputs",
      "旧ツール結果送信",
      "Assistants APIへツール結果を返す旧操作です。",
    ],
    [
      "migration-note",
      "migration note",
      "移行メモ",
      "旧APIから現在のAPIへ移る際の注意事項です。",
    ],
    [
      "deprecation-risk",
      "deprecation risk",
      "非推奨リスク",
      "旧APIが将来変更・終了する可能性に関する注意です。",
    ],
  ]),
] satisfies readonly LowerCategoryInventorySeed[];
