import {
  inventory,
  type LowerCategoryInventorySeed,
} from "@/lib/openai/api-setting-inventory-shared";

export const CHAT_COMPLETIONS_INVENTORY_SEEDS = [
  ...inventory(
    "chat-completions",
    "Chat Completions > Legacy inventory",
    "legacy",
    [
      [
        "model",
        "model",
        "旧APIモデル指定",
        "旧チャット補完で使うモデルを指定する項目です。",
      ],
      [
        "max-completion-tokens",
        "max_completion_tokens",
        "旧API最大出力トークン",
        "旧チャット補完の応答長上限です。",
      ],
      [
        "temperature",
        "temperature",
        "旧API生成の揺らぎ",
        "旧チャット補完で候補の選び方を調整する項目です。",
      ],
      [
        "top-p",
        "top_p",
        "旧API候補範囲",
        "旧チャット補完で単語候補の範囲を調整する項目です。",
      ],
      [
        "tools",
        "tools",
        "旧APIツール",
        "旧チャット補完でツール候補を渡す項目です。",
      ],
      [
        "tool-choice",
        "tool_choice",
        "旧APIツール選択",
        "旧チャット補完で使うツールを選ぶ項目です。",
      ],
      [
        "response-format",
        "response_format",
        "旧API応答形式",
        "旧チャット補完の返答形式を指定する項目です。",
      ],
      [
        "stop",
        "stop",
        "旧API停止条件",
        "旧チャット補完の生成を止める文字列候補です。",
      ],
      [
        "logprobs",
        "logprobs",
        "旧API候補確率",
        "旧チャット補完の候補確率情報です。",
      ],
      [
        "seed",
        "seed",
        "旧API再現用シード",
        "旧チャット補完の再現性に関係する項目です。",
      ],
      [
        "service-tier",
        "service_tier",
        "旧APIサービス階層",
        "旧チャット補完の処理階層に関係する項目です。",
      ],
      [
        "modalities",
        "modalities",
        "旧API出力モード",
        "旧チャット補完の出力種類を指定する候補です。",
      ],
      [
        "audio",
        "audio",
        "旧API音声出力",
        "旧チャット補完の音声出力に関係する候補です。",
      ],
    ],
  ),
] satisfies readonly LowerCategoryInventorySeed[];
